### ISSUE TITLE
Secrets are not removed on terraform destroy

### ISSUE THREAD

**Issue by lhriley** [1Password/terraform-provider-onepassword#26] opened 2021-05-19 19:55 UTC
### Your environment

Terraform Provider Version: `1.0.2`

Connect Server Version: `1.1.1` (container image: `sha256:aa808e82ff23b99574526dde1c18e5503c30f5f08eed0d1d5f2ce68f1441d3ed`)

OS:
```
cat /etc/lsb-release
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=20.1
DISTRIB_CODENAME=ulyssa
DISTRIB_DESCRIPTION="Linux Mint 20.1 Ulyssa"
```
Terraform Version: `v0.14.9`

## What happened?
Upon running the command `terraform destroy`, the logs indicate that the secrets have been deleted, but they remain in the 1password vault.

## What did you expect to happen?
The secrets are destroyed as indicated in the log messages.

OR

The documentation clearly outlines that secrets will not be deleted from the 1password vault on `terraform destroy`.

OR

(Preferred) An option exists in the Terraform provider resources which specifies the action that will be taken when a `destroy` action is required. Example:

```
resource "onepassword_item" "demo_login" {
  vault = var.vault_id

  remove_on_destroy = <bool>

  title    = "Demo Terraform Login"
  category = "password"

  username = "demo-username"

  password_recipe {
    length  = 40
    symbols = false
  }
}
```

## Steps to reproduce
1. Follow the example code here: https://github.com/1Password/terraform-provider-onepassword/tree/main/examples
2. Verify that the secrets are created in the appropriate 1password vault
3. Using a token with `delete` permissions, run the `terraform destroy` command
4. Verify that the logs indicate that the secrets were destroyed
5. Verify that the secrets remain available in the appropriate 1password vault

## Notes & Logs
Terraform destroy:
```
onepassword_item.demo_password: Destroying... [id=vaults/<uuid>/items/<uuid>]
onepassword_item.demo_login: Destroying... [id=vaults/<uuid>/items/<uuid>]
onepassword_item.demo_db: Destroying... [id=vaults/<uuid>/items/<uuid>]
onepassword_item.demo_sections: Destroying... [id=vaults/<uuid>/items/<uuid>]
onepassword_item.demo_login: Destruction complete after 0s
onepassword_item.demo_sections: Destruction complete after 1s
onepassword_item.demo_db: Destruction complete after 1s
onepassword_item.demo_password: Destruction complete after 1s
```

docker-compose (source: https://support.1password.com/connect-deploy-docker/#step-2-deploy-a-1password-connect-server):
```
op-connect-api_1   | {"log_message":"(I) DELETE /v1/vaults/<uuid>/items/<uuid>","timestamp":"2021-05-19T19:28:36.628298253Z","level":3,"scope":{"request_id":"<uuid>"}}
op-connect-api_1   | {"log_message":"(I) DELETE /v1/vaults/<uuid>/items/<uuid>","timestamp":"2021-05-19T19:28:36.628339326Z","level":3,"scope":{"request_id":"<uuid>"}}
op-connect-api_1   | {"log_message":"(I) DELETE /v1/vaults/<uuid>/items/<uuid>","timestamp":"2021-05-19T19:28:36.628298254Z","level":3,"scope":{"request_id":"<uuid>"}}
op-connect-api_1   | {"log_message":"(I) DELETE /v1/vaults/<uuid>/items/<uuid>","timestamp":"2021-05-19T19:28:36.6288812Z","level":3,"scope":{"request_id":"<uuid>"}}
op-connect-api_1   | {"log_message":"(I) DELETE /v1/vaults/<uuid>/items/<uuid> completed (204: No Content)","timestamp":"2021-05-19T19:28:37.266439816Z","level":3,"scope":{"request_id":"<uuid>","jti":"<uuid>"}}
op-connect-api_1   | {"log_message":"(I) DELETE /v1/vaults/<uuid>/items/<uuid> completed (204: No Content)","timestamp":"2021-05-19T19:28:37.552712026Z","level":3,"scope":{"request_id":"<uuid>","jti":"<uuid>"}}
op-connect-api_1   | {"log_message":"(I) DELETE /v1/vaults/<uuid>/items/<uuid> completed (204: No Content)","timestamp":"2021-05-19T19:28:37.868969691Z","level":3,"scope":{"request_id":"<uuid>","jti":"<uuid>"}}
op-connect-api_1   | {"log_message":"(I) DELETE /v1/vaults/<uuid>/items/<uuid> completed (204: No Content)","timestamp":"2021-05-19T19:28:38.15887181Z","level":3,"scope":{"request_id":"<uuid>","jti":"<uuid>"}}
```

**Comment by verkaufer** [comment] 2021-05-25 15:43
👋  Hello! Thank you for reporting this!

The problem is the result of some recent changes to [how items are Deleted vs Archived](https://blog.1password.com/introducing-archive/) in 1Password.

To address this change, we've done two things:
1. Released `v1.2.0` of the Connect server last week that now returns the correct error code when the DELETE request fails. 
2. Updated the web UI to include "Delete Items" as a permission when setting up a new Connect server.

### What this means for you
You will need to update the permissions for your Connect servers. Fortunately, adding the "Delete Items" permission is non-destructive and does not require you to rotate tokens.

**Via Web UI**

1. Log in to the Web UI: https://start.1password.com
2. In the right-hand sidebar, select `Integrations`. You should see a collection of all your active Integrations.
3. Click on the Connect server you want to edit
4. On the server details page, under the `Vault Access` heading, click the gear icon and modify the server's access to the relevant vaults.
5. Click on "Delete Items", in addition to "Archive Items"
6. Close the popover, which will automatically save your changes.

(Going forward, new Connect servers will have the correct "Delete" permissions, if granted in the setup wizard)

**Via CLI**
You can use the 1Password CLI to grant Read/Write/Delete permissions to the server. To change the vault permissions for a server, run:
```bash
op add connect server <service_account_id> <vault_id> 
```
Additional documentation for this command can be found in our [support library](https://support.1password.com/command-line-reference/#add-connect-server).

There is no fine-grained access control for vaults via the CLI at this time. If you did not intend for the server to have "Read" access, you will need to remove it through the web interface using the instructions I provided above.

---

Let us know if you have any additional questions.

**Comment by lhriley** [comment] 2021-05-25 18:54
@verkaufer That's great that you've identified and addressed the issue.

I have updated my permissions as suggested, but I don't have the bandwidth to verify the fix at the moment.

Since this appears to have been an issue with the 1password Connect Server, does that mean this issue would be fixed for all SDKs, and not just the Terraform provider?

Also, should I open a separate feature request for the flag to control deletion of secrets from vaults on destroy?

> (Preferred) An option exists in the Terraform provider resources which specifies the action that will be taken when a destroy action is required. Example:

**Comment by verkaufer** [comment] 2021-05-25 20:30
>Since this appears to have been an issue with the 1password Connect Server, does that mean this issue would be fixed for all SDKs, and not just the Terraform provider?

Correct :) 

>Also, should I open a separate feature request for the flag to control deletion of secrets from vaults on destroy?

That would be great. I'd like to have us explore the idea a little more before we commit, so a new feature request would be appreciated.

**Comment by lhriley** [comment] 2021-05-25 22:49
@verkaufer That's perfect. I was testing out the Python SDK and saw the same thing after I filed this, but didn't take the time to write up another issue.

I'll link the feature request back here once I've gotten it posted to make tracking easier.

Thanks again!

**Comment by verkaufer** [comment] 2021-05-27 15:59
Thanks for opening the feature request! I'm going to close this issue and move discussion over there.

**Closed by verkaufer** 2021-05-27 15:59 UTC
Labels: bug
