### ISSUE TITLE
If I use the vault name when defining an item, and rerun terraform, it wants to recreate the item as it has a diff with the vault name versus vault UUID

### ISSUE THREAD

**Issue by scott-doyland-burrows** [1Password/terraform-provider-onepassword#154] opened 2024-02-29 13:41 UTC
Terraform 1.7.4
Provider 1.4.2
OnePassword CLI 2.25.0

I use this code:

```
resource "onepassword_item" "item" {

  vault = "example-vault"

  category = "login"
  username = "mylogin"
  password = "mypassword
}
```

This works, but when I rerun an apply it says the resource must be replaced and shows this as a diff.

`~ vault    = "khubz3ahotlrg2ze2xveqkijhy" -> "example-vault" # forces replacement`

To fix this I must use the vault UUID rather than the vault name when creating the resource.

I should be able to use the vault name OR the vault UUID and not get a diff.

**Comment by edif2008** [comment] 2024-04-25 11:16
Closing this as a duplicate of #131.

**Closed by edif2008** 2024-04-25 11:16 UTC
Labels: bug
