### ISSUE TITLE
Feature Request: Service Account support

### ISSUE THREAD

**Issue by gabrielrinaldi** [1Password/terraform-provider-onepassword#79] opened 2023-05-08 00:48 UTC
### Summary
Is there a plan to add service account support to Terraform?

### Use cases
I have a private cluster and connection to 1Password would be a lot easier through a SA instead of having to deploy a Terraform Agent in the cluster

### Proposed solution
Add SA support to the Terraform provider

### Is there a workaround to accomplish this today?
Today I would have to deploy a Terraform Agent in the cluster and install the 1Password Operator to give access to secrets

### References & Prior Work
* GitHub Actions can use SA

**Comment by dustin-ruetz** [comment] 2023-05-26 19:13
Hi @gabrielrinaldi - thanks for reaching out with this feature request. I can confirm that using Service Accounts with Terraform is on our radar, but I can't provide any commitments or timelines as of this writing. Thank you again for expressing your interest!

**Comment by gabrielrinaldi** [comment] 2023-05-29 18:57
Thanks for getting back to me @dustin-ruetz, I think that would be game changing in replacing Vault (I was using that prior) as it would allow for more security and simplify password management incredibly. Please keep me posted as I am super interested in this.

**Comment by gabrielrinaldi** [comment] 2023-07-17 20:15
@dustin-ruetz is this something I could help with? I don't know how to build `terraform` providers, but I am willing to try as secrets are a little out of control given that I can't use them in Terraform unless I open `connect` to the internet.

**Comment by franklouwers** [comment] 2023-08-14 14:10
@dustin-ruetz Hi, would this still be on the short-term radar? I have a few customers where setting up and hosting a separated Connect wouldn't make a lot of sense, but using an SA would be the perfect solution.

**Comment by TakumiHaruta** [comment] 2023-08-20 05:43
This is really good. We're eagerly awaiting this feature!

**Comment by ekostjuk** [comment] 2023-08-25 15:14
Hacky ugly workaround:
Improved something that was previously shared on 1p slack by another dev: https://gist.github.com/ekostjuk/944d3c4483c1961fee805b66eb1679ac

**Comment by xophere** [comment] 2023-08-30 21:28
Yeah this provider is basically pointless without service account support.

**Comment by xophere** [comment] 2023-08-30 21:50
Yeah we just opted to use a different tool because the template process isn't gonna cut it.

**Comment by gabrielrinaldi** [comment] 2023-08-30 23:34
@xophere what vendor are you using? I am evaluating AWS Secrets and Vault Open Source as options this does not seem ready for production yet.

**Comment by xophere** [comment] 2023-08-31 00:19
Yeah just falling back to aws native secrets manager.  It simplifies somethings.  Also segregates corp secrets from platform ones.  But I still don't like multiple storage locations.  Looking into the template method via the cli tool.  It would work with a tfvars file.  But my boss just rejected it on principle.  More things to inject into the deployment process and the cli env for manual deployment.   I got more code to write now.  Really strange they bothered to make this module without this feature.   I suppose it just helps minimize tie in to 1password.  So dumb.  Can't be that many hours of dev time to make this work.

**Comment by alecsiemerink** [comment] 2023-08-31 14:21
We are eagerly awaiting this feature as well. If any help is needed with implementation, let us know. Without service account support, this provider is mostly useless unfortunately.

**Comment by dustin-ruetz** [comment] 2023-09-08 01:12
Thanks all for your patience on this issue 🙏 While I can’t share specifics on timelines, I can confirm that this feature is on our roadmap and is a high priority. With that being said, we have recently modernized our [CONTRIBUTING.md](https://github.com/1Password/terraform-provider-onepassword/blob/main/CONTRIBUTING.md) file as a starting point to help guide external contributors who are interesting in adding features.

CC @gabrielrinaldi @franklouwers @alecsiemerink

**Comment by tim-oster** [comment] 2023-09-11 12:54
Hey all, just opened a PR that adds basic Service Account support. Works in my setup but might need some improvements.

**Comment by gruizonestic** [comment] 2023-11-28 12:10
Are there any news on this matter? It would completely change the way we use 1Password and terraform together to store secrets in a very positive manner.

**Comment by dbrennand** [comment] 2023-11-28 22:37
#99 has been merged now so shouldn't be long before a new release is available 🙂

**Closed** 2023-11-29 00:36 UTC
Labels: enhancement, tracked

**Comment by volodymyrZotov** [comment] 2023-11-29 14:54
This is released in `v1.3.0`

**Comment by dbrennand** [comment] 2023-11-29 15:14
> This is released in `v1.3.0`

Thanks @volodymyrZotov @tim-oster 🚀
